# Generated by Django 3.1 on 2020-11-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Review'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='feature',
            new_name='featured',
        ),
    ]
