# Generated by Django 3.1 on 2020-11-30 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0005_auto_20201201_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='click.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='phn',
            field=models.BigIntegerField(verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Staff assigned', 'Staff assigned'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=256),
        ),
    ]
