# Generated by Django 3.1.3 on 2020-12-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0008_auto_20201210_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reason',
            field=models.TextField(default='null'),
        ),
    ]
