# Generated by Django 3.1.3 on 2020-12-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0011_auto_20201213_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile/profile.png', upload_to='profile'),
        ),
    ]
