# Generated by Django 3.1.3 on 2020-12-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0012_auto_20201213_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
