# Generated by Django 3.1.3 on 2020-12-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0013_auto_20201214_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
