# Generated by Django 3.1.3 on 2020-12-13 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('click', '0015_auto_20201214_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='click.booking'),
        ),
    ]
